### ISSUE TITLE
ZeroDivizionError when more than 10 NUMA nodes

### ISSUE THREAD

**Issue by alexnik66** [jhladka/MPSTAT2NODE#1]
Unfortunately MPSTAT2NODE gives ZeroDivizionError when used on system with more than 10  NUMA nodes. One can workaround this problem by changing the code on lines 104 and 106 from:
cpu_numa[str(i)] = words[1][-1:]
to:
cpu_numa[str(i)] = words[1][4:]

Best regards,
Alexey

**Comment by jhladka** [comment]
Hi Alexey,
I fixed it. Thanks!
Jarka
